In [1]:
# !pip install beautifulsoup4

In [2]:
# !pip install lxml

In [3]:
# from bs4 import BeautifulSoup
 
# with open('data/F24 - Aston Villa Women v Manchester City Women - 2124864.xml', 'r') as f:
#     event_data = f.read()

# Bs_data = BeautifulSoup(event_data, "xml")

In [4]:
# b_unique = Bs_data.find_all('Games')
# print(b_unique)

In [5]:
# b_unique = Bs_data.find_all('Event')
# print(b_unique)

In [6]:
# import pandas as pd

# df = pd.read_csv(r'data\opta-woman.csv')
# # print(df.head)
# df = df[df['Type_Id']=='2']
# df.head

### Convert to .csv

In [7]:
# import xml.etree.ElementTree as Xet
# import pandas as pd
  
# cols = ["event_id", "id", "outcome", "perdiod_id", "sec", "team_id", "timestamp", "type_id", "version", "x", "y"]
# rows = []
  
# # Parsing the XML file 
# # event_id="2" id="2208593383" last_modified="2020-09-05T14:33:15" min="0" outcome="1" period_id="1" sec="0" team_id="9673" 
# # timestamp="2020-09-05T14:33:15.328" type_id="32" version="1599312795441" x="0.0" y="0.0"
# xmlparse = Xet.parse('data/F24 - Aston Villa Women v Manchester City Women - 2124864.xml')
# root = xmlparse.getroot()
# print(root)
# for i in root:
#     event_id = i.find("event_id").text
#     id = i.find("id").text
#     outcome = i.find("outcome").text
#     period_id = i.find("period_id").text

  
#     rows.append({"event_id": event_id,
#                  "id": id,
#                  "outcome": outcome,
#                  "period_id": period_id,
#                 })
  
# df = pd.DataFrame(rows, columns=cols)
  
# # Writing dataframe to csv
# df.to_csv('output.csv')

In [10]:
import numpy as np
import pandas as pd

# data = pd.read_xml(path_or_buffer='data/TeamR v TeamS - MA3 - Event File.xml', xpath='/Games/Game/Event')
# data = pd.read_xml(path_or_buffer='data/TeamE v TeamF - MA3 - Event File.xml', xpath='/matchEvents/liveData/events')
event_data = pd.read_xml(path_or_buffer='data/TeamR v TeamS - MA3 - Event File.xml', xpath='/matchEvents/liveData/events/event')

#offside passes
df = event_data[event_data['typeId']==2]
df

,id,eventId,typeId,periodId,timeMin,timeSec,contestantId,outcome,x,y,timeStamp,lastModified,qualifier,playerId,keyPass
855,2211999879,511,2,1,44,38,2b3mar72yy8d6uvat1ka6tn3r,1,63.2,90.8,2020-09-16T19:45:48.636Z,2020-09-16T23:44:20Z,NaN,7glxasv2ed6ey82dknto1y66t,NaN
1099,2212007845,400,2,2,57,32,2khen2a38l2hkx33s73pehl6o,1,70.7,77.0,2020-09-16T20:17:06.228Z,2020-09-16T23:45:34Z,NaN,17acodpsoxkhha2iem2465ivp,NaN
1235,2212010221,442,2,2,65,35,2khen2a38l2hkx33s73pehl6o,1,65.1,37.1,2020-09-16T20:25:09.602Z,2020-09-17T01:36:44Z,NaN,bzupilj2z7w0nepi1ywy5hihh,NaN
1769,2212014773,627,2,2,93,57,2khen2a38l2hkx33s73pehl6o,1,43.4,42.5,2020-09-16T20:53:32.055Z,2020-09-17T00:21:23Z,NaN,blo3zmhar2mujyp9z7kjnsut,NaN

In [11]:
tracking_data = pd.read_csv(filepath_or_buffer='data/TeamR v TeamS - MA25 - Tracking File.txt', header=None, sep=',')
# tracking_data = tracking_data.columns['timestamp', 'frameCount', 'matchPeriod', 'matchStatus', 'players', 'ballPosition']

# Column 1: Timestamp
# Column 2: Elapsed time (frameCount)
# Column 3: Match period
# Column 4: Match status - paused/not paused
# Column 5: Players and Referees
# Column 5 - nested data: Players
# Column 5 - nested data: Referees
# Column 6: Ball position
# Understanding the tracking file data: X, Y, Z coordinates

tracking_data

C:\Users\admin\AppData\Local\Temp\ipykernel_14408\144392792.py:1: DtypeWarning: Columns (84,87,88,90,92) have mixed types. Specify dtype option on import or set low_memory=False.
  tracking_data = pd.read_csv(filepath_or_buffer='data/TeamR v TeamS - MA25 - Tracking File.txt', header=None, sep=',')

,0,1,2,3,4,5,6,7,8,9,...,83,84,85,86,87,88,89,90,91,92
0,1600286400000;0,1,0:0,7glxasv2ed6ey82dknto1y66t,11,52.310,9.714;0,e40eqhxzzid2chfyxph37tuxh,21,42.675,...,9sme7jykdv8msgfu0nxx6h39x,1,4.998,33.673;4,53tqqwl5dpxn0v5zluabsmms5,16,99.378,33.785;:52.26,34.10,0;
1,1600286400100;100,1,0:0,7glxasv2ed6ey82dknto1y66t,11,52.365,9.767;0,e40eqhxzzid2chfyxph37tuxh,21,42.676,...,9sme7jykdv8msgfu0nxx6h39x,1,5.016,33.701;4,53tqqwl5dpxn0v5zluabsmms5,16,99.370,33.78;:50.76,34.46,0;
2,1600286400200;200,1,0:0,7glxasv2ed6ey82dknto1y66t,11,52.421,9.817;0,e40eqhxzzid2chfyxph37tuxh,21,42.678,...,9sme7jykdv8msgfu0nxx6h39x,1,5.038,33.732;4,53tqqwl5dpxn0v5zluabsmms5,16,99.347,33.783;:49.48,34.63,0;
3,1600286400300;300,1,0:0,7glxasv2ed6ey82dknto1y66t,11,52.477,9.867;0,e40eqhxzzid2chfyxph37tuxh,21,42.685,...,9sme7jykdv8msgfu0nxx6h39x,1,5.063,33.764;4,53tqqwl5dpxn0v5zluabsmms5,16,99.306,33.798;:47.795,35.14,0;
4,1600286400400;400,1,0:0,7glxasv2ed6ey82dknto1y66t,11,52.531,9.914;0,e40eqhxzzid2chfyxph37tuxh,21,42.695,...,9sme7jykdv8msgfu0nxx6h39x,1,5.094,33.797;4,53tqqwl5dpxn0v5zluabsmms5,16,99.250,33.822;:46.62,35.27,0;
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57771,1600293013100;3013100,2,0:0,7glxasv2ed6ey82dknto1y66t,11,32.948,64.697;0,e40eqhxzzid2chfyxph37tuxh,21,71.399,...,53tqqwl5dpxn0v5zluabsmms5,16.0,18.625,41.552;:61.245,64.735,0;,NaN,NaN,NaN,NaN
57772,1600293013200;3013200,2,0:0,7glxasv2ed6ey82dknto1y66t,11,33.092,64.67;0,e40eqhxzzid2chfyxph37tuxh,21,71.371,...,53tqqwl5dpxn0v5zluabsmms5,16.0,18.626,41.542;:60.78,64.53,0;,NaN,NaN,NaN,NaN
57773,1600293013300;3013300,2,0:0,7glxasv2ed6ey82dknto1y66t,11,33.232,64.644;0,e40eqhxzzid2chfyxph37tuxh,21,71.360,...,53tqqwl5dpxn0v5zluabsmms5,16.0,18.629,41.542;:60.28,64.485,0;,NaN,NaN,NaN,NaN
57774,1600293013400;3013400,2,0:0,7glxasv2ed6ey82dknto1y66t,11,33.371,64.618;0,e40eqhxzzid2chfyxph37tuxh,21,71.363,...,53tqqwl5dpxn0v5zluabsmms5,16.0,18.632,41.546;:59.78,64.53,0;,NaN,NaN,NaN,NaN
57775,1600293013500;3013500,2,0:0,7glxasv2ed6ey82dknto1y66t,11,33.482,64.599;0,e40eqhxzzid2chfyxph37tuxh,21,71.374,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN